title: Michelle Lin # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software developer with 4+ years of experience in building and maintaining backend applications, with a passion for innovative problem-solving and a strong focus on delivering reliable, high-quality outcomes.
  <br><br>
  Proficient in Node.js, Python, and JavaScript, and experienced in DevOps practices.
  <br><br>
  <a href="https://www.linkedin.com/in/meichen--lin/">LinkedIn Profile</a> 
  
# remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
# plugins:
# - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'
